version: '3.8'

services:
  assignment_app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    volumes:
      - ./assignment:/assignment
    environment:
      - SECRET_KEY=justransomsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=dbdevelop
      - DB_USER=dbuser
      - DB_PASS=dbpassword
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_DB=dbdevelop
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
